version="1.28.0"

[x86_64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.28.0/linux/amd64/sysdig-cli-scanner"
hash="sha256-vfBo668L6G8+/91YZjfIibO5AGeSkJIT1uxE/N37r/s="

[aarch64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.28.0/linux/arm64/sysdig-cli-scanner"
hash="sha256-GmOasex0P7z0hy4RZpZ/DBtlGUHc84mwLz2R6cdyMmk="

[x86_64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.28.0/darwin/amd64/sysdig-cli-scanner"
hash="sha256-/ODlC2vJAThlxRmhGIXo5XX3XObGBMKb59DNdv0xNdY="

[aarch64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.28.0/darwin/arm64/sysdig-cli-scanner"
hash="sha256-ufys+j/GJa0bC23cXuMTaUOh8XSkXmPIKq6XcChti48="
