version="1.13.1"

[x86_64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.13.1/linux/amd64/sysdig-cli-scanner"
hash="sha256-DKro56x5DeHn0K6Izd3OpFSEosFy2jbeYXYzsHkIsbY="

[aarch64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.13.1/linux/arm64/sysdig-cli-scanner"
hash="sha256-Pflw5/XX6FoC96ElE11QPItJH02xcLnU1VycmSl4F28="

[x86_64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.13.1/darwin/amd64/sysdig-cli-scanner"
hash="sha256-L/ZovUSFU+RLnNn5MsNGeZ6L0pRK4wYW4a7BdcRwoVk="

[aarch64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/1.13.1/darwin/arm64/sysdig-cli-scanner"
hash="sha256-8o0Sw79JcIu/f48TJNsIwH8IiJZxSXGwqe86RCkAHM8="
