version="0.14.0"

[x86_64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/0.14.0/linux/amd64/sysdig-cli-scanner"
hash="sha256-LlpUvTXnwM+dxxdU0ahw/AjLMAQ3jZ6PBVevwaA49X4="

[aarch64-linux]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/0.14.0/linux/arm64/sysdig-cli-scanner"
hash="sha256-ZTH4bK+0/qtBMFsSeq68Aje1/eebXsW/0eKA8AQljRc="

[x86_64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/0.14.0/darwin/amd64/sysdig-cli-scanner"
hash="sha256-0XwqH5ARyTEMdjh08RVf1shOXAAVzMDs4rde5z/Lzck="

[aarch64-darwin]
url="https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/0.14.0/darwin/arm64/sysdig-cli-scanner"
hash="sha256-qVSipzinhhka3liBWP4kMQeK9ty4Wcx80Al8jiXnFFY="
